[package]
name = "rustgl"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.30.9"
gl = "0.14.0"
winit = "0.28.6"
glutin-winit = "0.3.0"
raw-window-handle = "0.5.2"
glm = "0.2.3"
image = "0.24.6"
thiserror = "1.0.44"
soloud = "1.0.2"
imgui = "0.11.0"

