[package]
name = "rustgl"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.30.9"
winit = "0.28.6"
glutin-winit = "0.3.0"
raw-window-handle = "0.5.2"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.1.1"
